kind: Service
apiVersion: v1
metadata:
  name: hello-graylog
  namespace: graylog
spec:
  type: LoadBalancer
  selector:
    app: hello-graylog
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web